# Generated by Django 5.1.4 on 2026-06-17 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_auto_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Max Limit Reached'), ('won', 'Won Auction'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gh_auto_bids',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('outbid', 'Outbid'), ('winning', 'Winning'), ('won', 'Won'), ('cancelled', 'Cancelled'), ('retracted', 'Retracted'), ('fraud', 'Flagged as Fraud')], default='active', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Bid'), ('auto', 'Auto-Bid'), ('buy_now', 'Buy Now')], default='manual', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('fraud_flags', models.JSONField(default=list)),
                ('triggered_extension', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gh_bids',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BidCreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('price_ghs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_credits', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'gh_bid_credit_packages',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BidCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive = credit, Negative = debit')),
                ('description', models.CharField(max_length=200)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gh_credit_transactions',
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('shill_bidding', 'Shill Bidding'), ('multi_account', 'Multiple Accounts'), ('bid_velocity', 'Abnormal Bid Velocity'), ('suspicious_pattern', 'Suspicious Bidding Pattern'), ('account_suspicious', 'Suspicious Account Activity')], max_length=50)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gh_fraud_flags',
            },
        ),
    ]
