# Generated by Django 5.1.4 on 2026-06-17 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('gh_auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autobid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to='gh_auctions.auction'),
        ),
        migrations.AddField(
            model_name='autobid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='gh_auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidcredittransaction',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.bid'),
        ),
        migrations.AddField(
            model_name='bidcredittransaction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.bidcreditpackage'),
        ),
        migrations.AddField(
            model_name='bidcredittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gh_auctions.auction'),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags_detail', to='bidding.bid'),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='autobid',
            unique_together={('auction', 'bidder')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'status'], name='gh_bids_auction_8d3919_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'status'], name='gh_bids_bidder__622dda_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='gh_bids_auction_eb7dfc_idx'),
        ),
    ]
