# Generated by Django 5.1.4 on 2026-06-17 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gh_accounts', '0001_initial'),
        ('gh_auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gh_auctions.auction'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('reviewer', 'seller', 'auction')},
        ),
    ]
