# Generated by Django 5.1.4 on 2026-06-17 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gh_auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gh_paystack_webhooks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('bid_win', 'Auction Win Payment'), ('buy_now', 'Buy Now Payment'), ('subscription', 'Subscription Plan'), ('bid_credits', 'Bid Credits'), ('featured_listing', 'Featured Listing Fee'), ('deposit', 'Security Deposit')], max_length=30)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card (Visa/Mastercard/Credit)'), ('bank_transfer', 'Bank Transfer'), ('mtn_momo', 'MTN Mobile Money'), ('telecel_cash', 'Telecel Cash'), ('airteltigo_money', 'AirtelTigo Money')], max_length=30)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_fee_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_to_seller_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('paystack_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('momo_number', models.CharField(blank=True, max_length=15)),
                ('momo_network', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gh_auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gh_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released to Seller'), ('disputed', 'Under Dispute'), ('refunded', 'Refunded to Buyer')], default='holding', max_length=20)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_date', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('dispute_raised_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='gh_auctions.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_seller', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='payments.payment')),
            ],
            options={
                'db_table': 'gh_escrow',
            },
        ),
        migrations.CreateModel(
            name='BankTransferInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Ghana Commercial Bank', max_length=100)),
                ('account_name', models.CharField(default='GhanaHammer Ltd Escrow', max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('sort_code', models.CharField(blank=True, max_length=20)),
                ('reference_code', models.CharField(max_length=50)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
            options={
                'db_table': 'gh_bank_transfers',
            },
        ),
    ]
