# Generated by Django 5.1.4 on 2026-06-17 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('gh_auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionview',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='gh_auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketanalytics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gh_auctions.category'),
        ),
        migrations.AddIndex(
            model_name='auctionview',
            index=models.Index(fields=['auction', 'viewed_at'], name='gh_auction__auction_7a6c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketanalytics',
            unique_together={('date', 'category')},
        ),
    ]
