# Generated by Django 5.1.4 on 2026-06-17 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ghana_card', 'Ghana Card (National ID)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voter_id', "Voter's ID Card"), ('business_registration', 'Business Registration Certificate')], max_length=30)),
                ('document_number', models.CharField(max_length=50)),
                ('front_image', models.ImageField(upload_to='kyc/%Y/%m/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/')),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/%Y/%m/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ghana_post_gps', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('tin_number', models.CharField(blank=True, max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gh_kyc_documents',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
